# This is a basic workflow to help you get started with Actions

name: CI_workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  var1: "It is a variable"

jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: step1
        run: echo "::set-output name=op1::Hello, New Relic"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: step2
        run: echo "::set-output name=op2::$var1"

    outputs:
      data1: ${{ steps.step1.outputs.op1 }}
      data2: ${{ steps.step2.outputs.op2 }}


  job2:
    needs: job1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run output from job1
        run: |
          echo ${{ needs.job1.outputs.data1 }}
          echo ${{ needs.job1.outputs.data2 }}


# for committing the existing files to another branch
  job3: 
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Create new branch
        run: |
          git checkout -b demobranch
          git push -u origin demobranch

      - name: Make changes and commit
        run: |
          git add .
          git commit -m "Made some changes"
          git push -u origin demobranch

  # job4:
  
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v3
  #       with:
  #         ref: master

  #     - name: Checkout target branch
  #       run: git checkout testing

  #     - name: Make changes and commit
  #       run: |
  #         git add .
  #         git commit -m "Made some changes"
  #         git push origin testing

